In [6]:
### Some initializations
import numpy as np
import random
import loli
import pickle
import copy as copy


In [7]:
# Generating Lorenz data: high frequency

rs=1
np.random.seed(rs)
size=100000
X_fine=np.zeros((size+1,6))
X_fine[0,:]=[1,0.97,0.99,-1,4,10]


for t in range(size):
    e_obs=np.random.multivariate_normal(np.zeros(6),0.001*np.eye(6))
    x_new=[X_fine[t,0]*0.95+0.05*X_fine[t,1],\
           0.125*X_fine[t,0]-0.005*X_fine[t,0]*X_fine[t,2]+0.995*X_fine[t,1]+0.0005*X_fine[t,4]**2,\
           0.005*X_fine[t,0]*X_fine[t,1]+0.98665*X_fine[t,2],\
           X_fine[t,3]*0.95+0.05*X_fine[t,4],\
           X_fine[t,3]*0.14-X_fine[t,3]*X_fine[t,5]*0.005+0.995*X_fine[t,4]+0.00025*X_fine[t,1]**2,\
           0.005*X_fine[t,3]*X_fine[t,4]+0.98665*X_fine[t,5]]
    X_fine[t+1,:]=x_new+e_obs


In [25]:
### That was for a coupled run

E=100
gap=1
gapsearch=2
n=30
Xtest=copy.copy(X_fine)
# Xtest=copy.copy(X)
np.random.seed(1)
## Collecting the indices of high environments with difference in variance
indices=np.zeros(2*E*6)
counter=0
dataX=[]
for d in range(6):
    print(d)
    vares=np.zeros((6,100000-n))
    for i in range(0,100000-n,gapsearch):
        inds=np.arange(i,i+n,gap)
        vares[:,i]=np.var(Xtest[inds,:],axis=0)  
    sortvares=np.argsort(vares[d,:] )
    np.random.seed(1)


    for e in range(E):
            p=sortvares[e]
            indices[counter]=p
            counter+=1
            inds=np.arange(p,p+n,gap)
            dataX.append(Xtest[inds,:])
            p=sortvares[-e-1]
            inds=np.arange(p,p+n,gap)
            indices[counter]=p
            counter+=1
            dataX.append(Xtest[inds,:])
            
        
        
        
for tar in range(6):
    dataY=[]
    for j in range(2*E*6):
        p=int(indices[j])
        inds=np.arange(p,p+n,gap)
        dataY.append((Xtest[inds+gap,tar]))
    rs=np.random.randint(low=1,high=1000)
#     rs=int(randomseeds[tar])
    plausibleS=loli.gauss(dataX,dataY,l=1,alpha=0.1,lam=0,B=1000,rs=rs)
    if len(plausibleS)==0:
        supphat=set()
    else:
        supphat=set.intersection(*plausibleS)

    print('Target',tar,supphat,plausibleS)

0
1
2
3
4
5
Target 0 {0, 1} [{0, 1}, {0, 1, 2}, {0, 1, 3}, {0, 1, 4}, {0, 1, 5}, {0, 1, 2, 3}, {0, 1, 2, 4}, {0, 1, 2, 5}, {0, 1, 3, 4}, {0, 1, 3, 5}, {0, 1, 4, 5}, {0, 1, 2, 3, 4}, {0, 1, 2, 3, 5}, {0, 1, 2, 4, 5}, {0, 1, 3, 4, 5}, {0, 1, 2, 3, 4, 5}]
Target 1 set() []
Target 2 {0, 1, 2} [{0, 1, 2, 3, 4}, {0, 1, 2, 3, 5}, {0, 1, 2, 4, 5}, {0, 1, 2, 3, 4, 5}]


KeyboardInterrupt: 

In [23]:
rs=5
tar=4
dataY=[]
for j in range(2*E*6):
    p=int(indices[j])
    inds=np.arange(p,p+n,gap)
    dataY.append((Xtest[inds+gap,tar]))
plausibleS=loli.gauss(dataX,dataY,l=1,alpha=0.1,lam=0,B=1000,rs=rs)
if len(plausibleS)==0:
    supphat=set()
else:
    supphat=set.intersection(*plausibleS)

print('Target',tar,supphat,plausibleS)

Target 4 set() []


In [9]:
### That was for a coupled run

E=100
gap=2 #The gap in sampling
gapsearch=5 # The gap when looking for high variance intervals
n=30
Xtest=copy.copy(X_fine)
# Xtest=copy.copy(X)
np.random.seed(42)
## Collecting the indices of high environments with difference in variance
indices=np.zeros(2*E*6)
counter=0
dataX=[]
for d in range(6):
    print(d)
    vares=np.zeros((6,100000-n))
    for i in range(0,100000-n,gapsearch):
        inds=np.arange(i,i+n,gap)
        vares[:,i]=np.var(Xtest[inds,:],axis=0)  
    sortvares=np.argsort(vares[d,:] )
    np.random.seed(1)


    for e in range(E):
            p=sortvares[e]
            indices[counter]=p
            counter+=1
            inds=np.arange(p,p+n,gap)
            dataX.append(Xtest[inds,:])
            sortvares=list(filter(lambda i: i not in inds, sortvares))
            p=sortvares[-e-1]
            inds=np.arange(p,p+n,gap)
            sortvares=list(filter(lambda i: i not in inds, sortvares))
            indices[counter]=p
            counter+=1
            dataX.append(Xtest[inds,:])
            
        
        
        
for tar in range(6):
    dataY=[]
    for j in range(2*E*6):
        p=int(indices[j])
        inds=np.arange(p,p+n,gap)
        dataY.append((Xtest[inds+gap,tar]))
    rs=np.random.randint(low=1,high=1000)
    plausibleS=loli.gauss(dataX,dataY,l=1,alpha=0.1,lam=0,B=500,rs=rs)
    if len(plausibleS)==0:
        supphat=set()
    else:
        supphat=set.intersection(*plausibleS)

    print('Target',tar,supphat,plausibleS)

0
1
2
3
4
5
Target 0 {0} [{0, 1}, {0, 1, 2}, {0, 1, 3}, {0, 1, 4}, {0, 1, 5}, {0, 1, 2, 4}, {0, 1, 2, 5}, {0, 1, 3, 4}, {0, 1, 3, 5}, {0, 1, 4, 5}, {0, 2, 3, 4}, {0, 1, 2, 3, 4}, {0, 1, 3, 4, 5}, {0, 1, 2, 3, 4, 5}]
Target 1 set() []
Target 2 {1, 2} [{0, 1, 2, 3}, {0, 1, 2, 5}, {1, 2, 3, 5}, {0, 1, 2, 3, 5}, {0, 1, 2, 4, 5}, {1, 2, 3, 4, 5}, {0, 1, 2, 3, 4, 5}]
Target 3 {3} [{3, 4}, {0, 3, 4}, {1, 3, 4}, {2, 3, 4}, {3, 4, 5}, {0, 1, 3, 4}, {0, 2, 3, 4}, {1, 2, 3, 4}, {1, 3, 4, 5}, {2, 3, 4, 5}, {0, 1, 2, 3, 4}, {0, 1, 2, 3, 5}, {0, 1, 3, 4, 5}, {0, 2, 3, 4, 5}, {1, 2, 3, 4, 5}, {0, 1, 2, 3, 4, 5}]
Target 4 set() []
Target 5 {4, 5} [{3, 4, 5}, {0, 2, 4, 5}, {0, 3, 4, 5}, {1, 3, 4, 5}, {2, 3, 4, 5}, {0, 1, 2, 4, 5}, {0, 1, 3, 4, 5}, {0, 2, 3, 4, 5}, {1, 2, 3, 4, 5}, {0, 1, 2, 3, 4, 5}]


In [47]:
np.random.multivariate_normal(np.zeros(6),0.001*np.eye(6))

array([-0.00957294, -0.01509258, -0.05437182,  0.02723789, -0.00558778,
       -0.02790112])

In [101]:
# What if we have more fine grained data?
# Generating coupled data: fine grained

rs=2
np.random.seed(rs)
size=200000
X_fine=np.zeros((size+1,6))
X_fine[0,:]=[1,0.97,0.99,-1,4,10]
X_obs=np.zeros((size,6))


for t in range(size):
    e=np.random.multivariate_normal(np.zeros(6),0.0001*np.eye(6))
#     e=np.zeros(6)
    e_obs=np.random.multivariate_normal(np.zeros(6),0.0001*np.eye(6))
    x_new=[X_fine[t,0]*0.95+0.05*X_fine[t,1]+e[0],\
           0.125*X_fine[t,0]-0.005*X_fine[t,0]*X_fine[t,2]+0.995*X_fine[t,1]+0.0005*X_fine[t,4]**2+e[1],\
           0.005*X_fine[t,0]*X_fine[t,1]+0.98665*X_fine[t,2]+e[2],\
           X_fine[t,3]*0.95+0.05*X_fine[t,4]+e[3],\
           X_fine[t,3]*0.14-X_fine[t,3]*X_fine[t,5]*0.005+0.995*X_fine[t,4]+0.00025*X_fine[t,1]**2+e[4],\
           0.005*X_fine[t,3]*X_fine[t,4]+0.98665*X_fine[t,5]+e[5]]
    X_fine[t+1,:]=x_new
#     X_obs[t,:]=copy.copy(X_fine[t+1,:])+e_obs


In [102]:
### That was for a coupled run

E=100
gap=1
gapsearch=2
n=20
Xtest=copy.copy(X_fine)
# Xtest=copy.copy(X)
np.random.seed(1)
## Collecting the indices of high environments with difference in variance
indices=np.zeros(2*E*6)
counter=0
dataX=[]
for d in range(6):
    print(d)
    vares=np.zeros((6,size-n))
    for i in range(0,size-n,gapsearch):
        inds=np.arange(i,i+n,gap)
        vares[:,i]=np.var(Xtest[inds,:],axis=0)  
    sortvares=np.argsort(vares[d,:] )
    np.random.seed(1)


    for e in range(E):
            p=sortvares[e]
            indices[counter]=p
            counter+=1
            inds=np.arange(p,p+n,gap)
            dataX.append(Xtest[inds,:])
            p=sortvares[-e-1]
            inds=np.arange(p,p+n,gap)
            indices[counter]=p
            counter+=1
            dataX.append(Xtest[inds,:])
            
        
        
        
for tar in range(6):
    dataY=[]
    for j in range(2*E*6):
        p=int(indices[j])
        inds=np.arange(p,p+n,gap)
#         dataY.append((Xtest[inds+gap,tar]+np.random.multivariate_normal(np.zeros(len(inds)),0.0001*np.eye(len(inds)))))
        dataY.append((Xtest[inds+gap,tar]))
    rs=np.random.randint(low=1,high=1000)
    plausibleS=loli.gauss(dataX,dataY,l=1,alpha=0.1,lam=0,B=1000,rs=rs)
    if len(plausibleS)==0:
        supphat=set()
    else:
        supphat=set.intersection(*plausibleS)

    print('Target',tar,supphat,plausibleS)

0
1
2
3
4
5
Target 0 {0, 1} [{0, 1}, {0, 1, 2}, {0, 1, 3}, {0, 1, 4}, {0, 1, 5}, {0, 1, 2, 3}, {0, 1, 2, 4}, {0, 1, 2, 5}, {0, 1, 3, 4}, {0, 1, 3, 5}, {0, 1, 4, 5}, {0, 1, 2, 3, 4}, {0, 1, 2, 3, 5}, {0, 1, 2, 4, 5}, {0, 1, 3, 4, 5}, {0, 1, 2, 3, 4, 5}]
Target 1 {1, 2, 3, 5} [{1, 2, 3, 5}, {0, 1, 2, 3, 5}, {1, 2, 3, 4, 5}, {0, 1, 2, 3, 4, 5}]
Target 2 {1, 2} [{0, 1, 2}, {0, 1, 2, 3}, {0, 1, 2, 4}, {0, 1, 2, 5}, {1, 2, 3, 4}, {0, 1, 2, 3, 4}, {0, 1, 2, 3, 5}, {0, 1, 2, 4, 5}, {1, 2, 3, 4, 5}, {0, 1, 2, 3, 4, 5}]
Target 3 {3} [{3, 4}, {0, 3, 4}, {1, 3, 4}, {2, 3, 4}, {3, 4, 5}, {0, 1, 3, 4}, {0, 2, 3, 4}, {0, 3, 4, 5}, {1, 2, 3, 4}, {1, 3, 4, 5}, {2, 3, 4, 5}, {0, 1, 2, 3, 4}, {0, 1, 2, 3, 5}, {0, 1, 3, 4, 5}, {0, 2, 3, 4, 5}, {1, 2, 3, 4, 5}, {0, 1, 2, 3, 4, 5}]
Target 4 {0, 1, 2, 3, 4, 5} [{0, 1, 2, 3, 4, 5}]
Target 5 {4, 5} [{3, 4, 5}, {0, 1, 4, 5}, {0, 2, 4, 5}, {0, 3, 4, 5}, {1, 2, 4, 5}, {1, 3, 4, 5}, {2, 3, 4, 5}, {0, 1, 2, 4, 5}, {0, 1, 3, 4, 5}, {0, 2, 3, 4, 5}, {1, 2, 3, 4, 5}, 

In [88]:
for tar in range(6):
    dataY=[]
    for j in range(2*E*6):
        p=int(indices[j])
        inds=np.arange(p,p+n,gap)
        dataY.append((Xtest[inds+gap,tar]+np.random.multivariate_normal(np.zeros(len(inds)),0.0001*np.eye(len(inds)))))
    rs=np.random.randint(low=1,high=1000)
    plausibleS=loli.gauss(dataX,dataY,l=1,alpha=0.1,lam=0,B=500,rs=rs)
    if len(plausibleS)==0:
        supphat=set()
    else:
        supphat=set.intersection(*plausibleS)

    print('Target',tar,supphat,plausibleS)

Target 0 {0, 1} [{0, 1, 2}, {0, 1, 3}, {0, 1, 4}]
Target 1 set() []
Target 2 set() []
Target 3 {3, 4} [{3, 4}, {0, 3, 4}, {1, 3, 4}, {2, 3, 4}, {3, 4, 5}, {0, 1, 3, 4}, {0, 2, 3, 4}, {0, 3, 4, 5}, {1, 2, 3, 4}, {1, 3, 4, 5}, {2, 3, 4, 5}, {0, 1, 2, 3, 4}, {0, 1, 3, 4, 5}, {0, 2, 3, 4, 5}, {1, 2, 3, 4, 5}, {0, 1, 2, 3, 4, 5}]
Target 4 set() []
Target 5 set() []


In [58]:
for tar in range(6):
    dataY=[]
    for j in range(2*E*6):
        p=int(indices[j])
        inds=np.arange(p,p+n,gap)
        dataY.append((Xtest[inds+gap,tar]))
    rs=np.random.randint(low=1,high=1000)
    plausibleS=loli.gauss(dataX,dataY,l=1,alpha=0.01,lam=0,B=1000,rs=rs)
    if len(plausibleS)==0:
        supphat=set()
    else:
        supphat=set.intersection(*plausibleS)

    print('Target',tar,supphat,plausibleS)

Target 0 {0, 1, 3, 5} [{0, 1, 3, 5}, {0, 1, 2, 3, 5}, {0, 1, 3, 4, 5}, {0, 1, 2, 3, 4, 5}]
Target 1 set() []
Target 2 set() []
Target 3 {3, 4} [{3, 4}, {0, 3, 4}, {1, 3, 4}, {2, 3, 4}, {3, 4, 5}, {0, 1, 3, 4}, {0, 2, 3, 4}, {0, 3, 4, 5}, {1, 2, 3, 4}, {1, 3, 4, 5}, {2, 3, 4, 5}, {0, 1, 2, 3, 4}, {0, 1, 3, 4, 5}, {0, 2, 3, 4, 5}, {1, 2, 3, 4, 5}, {0, 1, 2, 3, 4, 5}]


KeyboardInterrupt: 

In [41]:
X_obs

array([ 8.27235229,  7.53715543, 25.72265678,  1.38475748,  3.39527467,
       21.62093045])

In [28]:
tar=1
dataY=[]
for j in range(2*E*6):
    p=int(indices[j])
    inds=np.arange(p,p+n,gap)
    dataY.append((Xtest[inds+gap,tar]))
rs=np.random.randint(low=1,high=1000)
plausibleS=loli.gauss(dataX,dataY,l=1,alpha=0.1,lam=0,B=1000)
if len(plausibleS)==0:
    supphat=set()
else:
    supphat=set.intersection(*plausibleS)

print('Target',tar,supphat,plausibleS)

Target 1 set() []


In [29]:
X_fine[:10,:]

array([[ 1.        ,  0.97      ,  0.99      , -1.        ,  4.        ,
        10.        ],
       [ 1.04986631,  1.07385456,  0.96493124, -0.78393025,  3.91760182,
         9.77371896],
       [ 1.10624152,  1.17825566,  0.96777533, -0.55673943,  3.87309735,
         9.56273681],
       [ 1.0996465 ,  1.30064718,  0.99722565, -0.3700292 ,  3.79730252,
         9.39653242],
       [ 1.11103145,  1.45175677,  0.95625931, -0.12546328,  3.77283059,
         9.27995341],
       [ 1.15655528,  1.5635605 ,  0.94767185,  0.03985979,  3.73427858,
         9.17047059],
       [ 1.15503331,  1.6892579 ,  0.92233185,  0.19785298,  3.69874441,
         9.04838855],
       [ 1.14641208,  1.83411738,  0.97226202,  0.39636305,  3.69364588,
         8.90318231],
       [ 1.15717013,  2.02301687,  0.97140227,  0.54108362,  3.71990229,
         8.85806085],
       [ 1.20426222,  2.17836417,  0.97963114,  0.68888543,  3.71798328,
         8.73882244]])